dependencies:
  - python=2.7.*
  - pip:
    - nteract_on_jupyter==1.8.1
    - colorama==0.3.9
    - numpy==1.14.5
    - scikit-learn==0.19.2
    - scipy==1.1.0
    - tensorflow==1.9.0
    - matplotlib==2.2.3
